stages:
  data_ingestion:
    cmd: .venv/bin/python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/Churn prediction DataSet.csv
    outs:
      - data/raw/ingested.csv

  preprocessing:
    cmd: .venv/bin/python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/ingested.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  training:
    cmd: .venv/bin/python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/best_model.joblib

  evaluation:
    cmd: .venv/bin/python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/best_model.joblib
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/metrics.json